INPUT_HEADER = {
    'CMTE_ID':0,
    'ZIP_CODE':10,
    'TRANSACTION_DT':13,
    'TRANSACTION_AMT':14,
    'OTHER_ID':15
}

INFO_HEADER = ['CMTE_ID', 'TRANSACTION_AMT', 'ZIP_CODE', 'TRANSACTION_DT']

COLSIZE = 21
